name 'chef-misc'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-misc'
long_description 'Installs/Configures chef-misc'
version '0.1.0'
