---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    network:
    - ["private_network", {ip: "192.168.1.107"}]

suites:
  - name: default
    run_list:
      - recipe[htcondor::default]
    attributes:
